### ISSUE TITLE
Class Cast issue for DDMFieldsCounter

### ISSUE THREAD

**Issue by sachanurag** [limburgie/com.liferay.dynamic.data.mapping.field.extender#3]
Hi,

I am facing a class cast issue for DDMFieldsCounter while trying to implements this extender solution.

Liferay does not allowed us to use internal service of above mentioned class. So I tried to use DDM API for the same but getting below mentioned error while creating the web-content using the structure which had custom attributes.

2019-01-18 13:31:39.288 ERROR [http-nio-8080-exec-8][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureKey=35873&p_p_auth=LiPcNPhi generates exception: com.liferay.portal.kernel.exception.PortalException: java.lang.ClassCastException: com.liferay.dynamic.data.mapping.util.DDMFieldsCounter cannot be cast to com.liferay.dynamic.data.mapping.internal.util.DDMFieldsCounter
java.lang.ClassCastException: com.liferay.dynamic.data.mapping.util.DDMFieldsCounter cannot be cast to com.liferay.dynamic.data.mapping.internal.util.DDMFieldsCounter
	at com.liferay.dynamic.data.mapping.internal.render.DDMFormFieldFreeMarkerRenderer.getFieldsCounter(DDMFormFieldFreeMarkerRenderer.java:451)
	at com.liferay.dynamic.data.mapping.internal.render.DDMFormFieldFreeMarkerRenderer.getFieldHTML(DDMFormFieldFreeMarkerRenderer.java:306)
	at com.liferay.dynamic.data.mapping.internal.render.DDMFormFieldFreeMarkerRenderer.render(DDMFormFieldFreeMarkerRenderer.java:114)
	at com.liferay.dynamic.data.mapping.internal.render.DDMFormRendererImpl.render(DDMFormRendererImpl.java:59)
	at com.liferay.dynamic.data.mapping.render.DDMFormRendererUtil.render(DDMFormRendererUtil.java:37)
	at org.apache.jsp.html.start_jsp._jspService(start_jsp.java:411)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:345)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:356)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:118)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)

**Comment by gvernile** [comment]
i get the same error on Liferay 7.1

**Comment by gvernile** [comment]
on rest ddm field and in the user ddm field

**Comment by sachanurag** [comment]
They will resolve it in Fix pack 8 release

**Comment by gvernile** [comment]
and when will be released fix pack 8?

**Comment by sachanurag** [comment]
Not sure about exact date may be in March

**Comment by gvernile** [comment]
but you are talking about liferay fix pack or about this project?!

**Comment by sachanurag** [comment]
I am talking about Liferay Portal fix pack.
No problem with this project

**Comment by gvernile** [comment]
ok. so until the fix pack 8 we never be able to add custom DDM Form Field?

**Comment by sachanurag** [comment]
Yes.

**Comment by gvernile** [comment]
ok. this is very bad. It was a main requirement into my project.
